/**
 * Created by miler_8zu3w9c on 7/12/2017.
 */
public with sharing class EmailManager {

	public static void sendMail(String address, String subject, String body){
		Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
		String[] toAddress = new String[] {address};
		mail.setToAddresses(toAddress);
		mail.setSubject(subject);
		mail.setPlainTextBody(body);
		Messaging.sendEmail(new Messaging.SingleEmailMessage[]{mail});

	}

}